### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by adam5525** [whataudoinghere/CPL-Translation#14]
Hi. I am sending you a corrected, full Polish language to the CPL

[strings.zip](https://github.com/whataudoinghere/CPL-Translation/files/3389789/strings.zip)

**Comment by rookielucky** [comment]
Hi Adam! Can you explain me how I should install/or where I must copying this translation file in my CPL?

**Comment by adam5525** [comment]
I did the translation in the Apk Editor pro application. Others had no problem adding such a translation. I can send you a compiled CPL application with added language.
[CPL.apk](https://github.com/whataudoinghere/CPL-Translation/files/3436724/CPL_Polish_language.apk.zip)
